server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  jpa:
    open-in-view: off
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mockwebsis
    username: josemaria
    password: maria17