server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  jpa:
    open-in-view: off
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mockwebsis

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html